import JSZip from "jszip";

interface ScreenCode {
  screenName: string;
  componentName: string;
  code: string;
}

interface AssembleOptions {
  appName: string;
  screens: ScreenCode[];
  screenshots: { name: string; url?: string }[];
}

function toSlug(name: string) {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

function buildPackageJson(appName: string) {
  return JSON.stringify(
    {
      name: toSlug(appName),
      version: "1.0.0",
      main: "expo-router/entry",
      scripts: {
        start: "expo start",
        android: "expo start --android",
        ios: "expo start --ios",
        web: "expo start --web",
      },
      dependencies: {
        expo: "~52.0.0",
        "expo-router": "~4.0.0",
        "expo-status-bar": "~2.0.1",
        react: "18.3.1",
        "react-native": "0.76.5",
        "react-native-safe-area-context": "4.12.0",
        "react-native-screens": "~4.1.0",
      },
      devDependencies: {
        "@babel/core": "^7.25.2",
        "@types/react": "~18.3.12",
        typescript: "^5.3.3",
      },
    },
    null,
    2
  );
}

function buildAppJson(appName: string) {
  return JSON.stringify(
    {
      expo: {
        name: appName,
        slug: toSlug(appName),
        version: "1.0.0",
        orientation: "portrait",
        icon: "./assets/icon.png",
        userInterfaceStyle: "dark",
        splash: { image: "./assets/splash.png", resizeMode: "contain", backgroundColor: "#080818" },
        ios: { supportsTablet: true },
        android: { adaptiveIcon: { foregroundImage: "./assets/adaptive-icon.png", backgroundColor: "#080818" } },
        web: { bundler: "metro" },
      },
    },
    null,
    2
  );
}

function buildEasJson() {
  return JSON.stringify(
    {
      cli: { version: ">= 12.0.0" },
      build: {
        development: { developmentClient: true, distribution: "internal" },
        preview: { distribution: "internal" },
        production: {},
      },
      submit: { production: {} },
    },
    null,
    2
  );
}

function buildTsConfig() {
  return JSON.stringify(
    {
      extends: "expo/tsconfig.base",
      compilerOptions: { strict: true },
    },
    null,
    2
  );
}

function buildAppLayout(screens: ScreenCode[]) {
  const imports = screens
    .map((s) => `import ${s.componentName} from "../screens/${s.componentName}";`)
    .join("\n");

  const tabs = screens
    .map(
      (s) =>
        `        <Tab.Screen name="${s.screenName}" component={${s.componentName}} />`
    )
    .join("\n");

  return `import React from "react";
import { createBottomTabNavigator } from "@react-navigation/bottom-tabs";
import { NavigationContainer } from "@react-navigation/native";
${imports}

const Tab = createBottomTabNavigator();

export default function App() {
  return (
    <NavigationContainer>
      <Tab.Tabs
        screenOptions={{ headerShown: false, tabBarStyle: { display: "none" } }}
      >
${tabs}
      </Tab.Tabs>
    </NavigationContainer>
  );
}
`;
}

function buildBabelConfig() {
  return `module.exports = function(api) {
  api.cache(true);
  return {
    presets: ["babel-preset-expo"],
  };
};
`;
}

export async function assembleExpoZip(options: AssembleOptions): Promise<Buffer> {
  const { appName, screens } = options;
  const zip = new JSZip();

  zip.file("package.json", buildPackageJson(appName));
  zip.file("app.json", buildAppJson(appName));
  zip.file("eas.json", buildEasJson());
  zip.file("tsconfig.json", buildTsConfig());
  zip.file("babel.config.js", buildBabelConfig());

  zip.file("app/_layout.tsx", buildAppLayout(screens));

  for (const screen of screens) {
    zip.file(`screens/${screen.componentName}.tsx`, screen.code);
  }

  zip.file(
    "assets/.gitkeep",
    "# Place icon.png, splash.png, adaptive-icon.png here\n"
  );

  zip.file(
    "README.md",
    `# ${appName}\n\nGenerated by [Evermade](https://evermade.app) — AI-powered mobile app builder.\n\n## Getting started\n\n\`\`\`bash\nnpm install\nnpx expo start\n\`\`\`\n`
  );

  const buffer = await zip.generateAsync({ type: "nodebuffer", compression: "DEFLATE" });
  return buffer;
}
