export type ComponentPlatform =
  | "mobile"
  | "dashboard"
  | "shared"
  | "auth"
  | "commerce"
  | "navigation"
  | "ai";

export interface ComponentRegistryEntry {
  id: string;
  name: string;
  category: string;
  platform: ComponentPlatform;
  styleTags: string[];
  description: string;
  filePath: string;
  isMobileSafe: boolean;
  isDecorative: boolean;
}

export const componentRegistry: ComponentRegistryEntry[] = [
  // ── Buttons ──────────────────────────────────────────────────────────
  {
    id: "cta-switch-toggle-button",
    name: "CtaSwitchToggleButton",
    category: "buttons",
    platform: "shared",
    styleTags: ["dark", "toggle", "neumorphic"],
    description: "Dark neumorphic toggle switch with animated knob.",
    filePath: "components/evermade/buttons/CtaSwitchToggleButton.tsx",
    isMobileSafe: true,
    isDecorative: false,
  },
  {
    id: "cta-glow-arrow-button",
    name: "CtaGlowArrowButton",
    category: "buttons",
    platform: "shared",
    styleTags: ["gradient", "glow", "arrow", "cta"],
    description: "Gradient glow button with animated arrow on hover.",
    filePath: "components/evermade/buttons/CtaGlowArrowButton.tsx",
    isMobileSafe: true,
    isDecorative: false,
  },
  {
    id: "secondary-simple-button",
    name: "SecondarySimpleButton",
    category: "buttons",
    platform: "shared",
    styleTags: ["zinc", "minimal", "border"],
    description: "Simple zinc-border secondary button with lift hover effect.",
    filePath: "components/evermade/buttons/SecondarySimpleButton.tsx",
    isMobileSafe: true,
    isDecorative: false,
  },
  {
    id: "secondary-rainbow-github-button",
    name: "SecondaryRainbowGithubButton",
    category: "buttons",
    platform: "shared",
    styleTags: ["rainbow", "github", "animated", "border"],
    description: "Rainbow animated border GitHub stars button.",
    filePath: "components/evermade/buttons/SecondaryRainbowGithubButton.tsx",
    isMobileSafe: false,
    isDecorative: false,
  },
  {
    id: "loading-dashed-spinner",
    name: "LoadingDashedSpinner",
    category: "buttons",
    platform: "shared",
    styleTags: ["loading", "dashed", "yellow", "spinner"],
    description: "Yellow dashed spinning ring loading indicator.",
    filePath: "components/evermade/buttons/LoadingDashedSpinner.tsx",
    isMobileSafe: true,
    isDecorative: true,
  },
  {
    id: "loading-spectrum-ring-spinner",
    name: "LoadingSpectrumRingSpinner",
    category: "buttons",
    platform: "shared",
    styleTags: ["loading", "spectrum", "colorful", "spinner"],
    description: "Multi-color spectrum glow ring spinner.",
    filePath: "components/evermade/buttons/LoadingSpectrumRingSpinner.tsx",
    isMobileSafe: true,
    isDecorative: true,
  },
  {
    id: "pill-generate-button",
    name: "PillGenerateButton",
    category: "buttons",
    platform: "ai",
    styleTags: ["pill", "sparkle", "gradient", "ai"],
    description: "Dark pill button with sparkle icon that glows purple on hover.",
    filePath: "components/evermade/buttons/PillGenerateButton.tsx",
    isMobileSafe: true,
    isDecorative: false,
  },
  {
    id: "pill-explore-button",
    name: "PillExploreButton",
    category: "buttons",
    platform: "shared",
    styleTags: ["pill", "elegant", "dark"],
    description: "Elegant pill-shaped explore button with subtle border animation.",
    filePath: "components/evermade/buttons/PillExploreButton.tsx",
    isMobileSafe: true,
    isDecorative: false,
  },
  {
    id: "gradient-generate-button",
    name: "GradientGenerateButton",
    category: "buttons",
    platform: "ai",
    styleTags: ["gradient", "animated-letters", "ai", "dark"],
    description: "Dark button with animated letter-gradient Generate text and flicker icon.",
    filePath: "components/evermade/buttons/GradientGenerateButton.tsx",
    isMobileSafe: false,
    isDecorative: false,
  },
  {
    id: "gradient-start-button",
    name: "GradientStartButton",
    category: "buttons",
    platform: "shared",
    styleTags: ["green", "gradient", "grid-pattern"],
    description: "Green gradient start button with grid pattern background.",
    filePath: "components/evermade/buttons/GradientStartButton.tsx",
    isMobileSafe: true,
    isDecorative: false,
  },

  // ── Inputs / Controls ──────────────────────────────────────────────
  {
    id: "chat-attach-input",
    name: "ChatAttachInput",
    category: "inputs",
    platform: "ai",
    styleTags: ["dark", "chat", "attachment", "input"],
    description: "Dark chat input bar with file attachment and send button.",
    filePath: "components/evermade/inputs/ChatAttachInput.tsx",
    isMobileSafe: true,
    isDecorative: false,
  },
  {
    id: "soft-pill-input",
    name: "SoftPillInput",
    category: "inputs",
    platform: "shared",
    styleTags: ["pill", "inset", "dark"],
    description: "Soft pill-shaped input with inset shadow on dark background.",
    filePath: "components/evermade/inputs/SoftPillInput.tsx",
    isMobileSafe: true,
    isDecorative: false,
  },
  {
    id: "search-glass-input",
    name: "SearchGlassInput",
    category: "inputs",
    platform: "navigation",
    styleTags: ["search", "glass", "gradient-border"],
    description: "Search input with glowing gradient border and filter icon.",
    filePath: "components/evermade/inputs/SearchGlassInput.tsx",
    isMobileSafe: false,
    isDecorative: false,
  },
  {
    id: "gradient-range-slider",
    name: "GradientRangeSlider",
    category: "inputs",
    platform: "shared",
    styleTags: ["slider", "gradient", "colorful"],
    description: "Rainbow gradient range slider with custom thumb.",
    filePath: "components/evermade/inputs/GradientRangeSlider.tsx",
    isMobileSafe: true,
    isDecorative: false,
  },
  {
    id: "upload-dropzone",
    name: "UploadDropzone",
    category: "inputs",
    platform: "shared",
    styleTags: ["upload", "drag-drop", "dashed"],
    description: "Dashed border drag & drop file upload zone.",
    filePath: "components/evermade/inputs/UploadDropzone.tsx",
    isMobileSafe: false,
    isDecorative: false,
  },
  {
    id: "upload-folder-selector",
    name: "UploadFolderSelector",
    category: "inputs",
    platform: "shared",
    styleTags: ["upload", "folder", "animated"],
    description: "Animated floating folder with file chooser button.",
    filePath: "components/evermade/inputs/UploadFolderSelector.tsx",
    isMobileSafe: false,
    isDecorative: false,
  },
  {
    id: "toggle-metal-switch",
    name: "ToggleMetalSwitch",
    category: "inputs",
    platform: "shared",
    styleTags: ["toggle", "metal", "skeuomorphic"],
    description: "Metallic skeuomorphic toggle switch with conic gradient handle.",
    filePath: "components/evermade/inputs/ToggleMetalSwitch.tsx",
    isMobileSafe: true,
    isDecorative: false,
  },
  {
    id: "toggle-neumorphic-switch",
    name: "ToggleNeumorphicSwitch",
    category: "inputs",
    platform: "shared",
    styleTags: ["toggle", "neumorphic", "3d", "animated"],
    description: "3D neumorphic toggle switch with elastic spring animation.",
    filePath: "components/evermade/inputs/ToggleNeumorphicSwitch.tsx",
    isMobileSafe: true,
    isDecorative: false,
  },

  // ── Cards ──────────────────────────────────────────────────────────
  {
    id: "chat-composer-card",
    name: "ChatComposerCard",
    category: "cards",
    platform: "ai",
    styleTags: ["chat", "composer", "dark", "ai"],
    description: "AI chat composer card with gradient border and action tags.",
    filePath: "components/evermade/cards/ChatComposerCard.tsx",
    isMobileSafe: true,
    isDecorative: false,
  },
  {
    id: "glass-stack-card",
    name: "GlassStackCard",
    category: "cards",
    platform: "shared",
    styleTags: ["glass", "frosted", "stack", "hover"],
    description: "Three frosted glass cards that fan out on hover.",
    filePath: "components/evermade/cards/GlassStackCard.tsx",
    isMobileSafe: false,
    isDecorative: true,
  },
  {
    id: "sales-metric-card",
    name: "SalesMetricCard",
    category: "cards",
    platform: "dashboard",
    styleTags: ["metric", "sales", "progress", "white"],
    description: "White card displaying sales metric with progress bar.",
    filePath: "components/evermade/cards/SalesMetricCard.tsx",
    isMobileSafe: true,
    isDecorative: false,
  },
  {
    id: "skeuomorphic-inset-card",
    name: "SkeuomorphicInsetCard",
    category: "cards",
    platform: "shared",
    styleTags: ["skeuomorphic", "inset", "shadow"],
    description: "Deeply-inset shadow skeuomorphic card.",
    filePath: "components/evermade/cards/SkeuomorphicInsetCard.tsx",
    isMobileSafe: true,
    isDecorative: true,
  },
  {
    id: "flip-food-card",
    name: "FlipFoodCard",
    category: "cards",
    platform: "mobile",
    styleTags: ["flip", "3d", "food", "dark"],
    description: "3D flip card showing rotating back and food front face.",
    filePath: "components/evermade/cards/FlipFoodCard.tsx",
    isMobileSafe: true,
    isDecorative: true,
  },
  {
    id: "kpi-glow-card",
    name: "KpiGlowCard",
    category: "cards",
    platform: "dashboard",
    styleTags: ["kpi", "glow", "animated-dot", "dark"],
    description: "Dark KPI card with animated dot border and gradient text value.",
    filePath: "components/evermade/cards/KpiGlowCard.tsx",
    isMobileSafe: false,
    isDecorative: false,
  },
  {
    id: "neumorph-dark-card",
    name: "NeumorphDarkCard",
    category: "cards",
    platform: "shared",
    styleTags: ["neumorphic", "dark", "minimal"],
    description: "Dark neumorphic card with double shadow.",
    filePath: "components/evermade/cards/NeumorphDarkCard.tsx",
    isMobileSafe: true,
    isDecorative: true,
  },
  {
    id: "premium-ribbon-card",
    name: "PremiumRibbonCard",
    category: "cards",
    platform: "commerce",
    styleTags: ["ribbon", "premium", "dark", "gradient"],
    description: "Dark card with orange gradient Premium corner ribbon.",
    filePath: "components/evermade/cards/PremiumRibbonCard.tsx",
    isMobileSafe: true,
    isDecorative: false,
  },

  // ── Feedback ───────────────────────────────────────────────────────
  {
    id: "pulse-bars-loader",
    name: "PulseBarsLoader",
    category: "feedback",
    platform: "shared",
    styleTags: ["loading", "bars", "pulse", "neon"],
    description: "Neon pulsing bars loading animation in blue spectrum.",
    filePath: "components/evermade/feedback/PulseBarsLoader.tsx",
    isMobileSafe: true,
    isDecorative: true,
  },
  {
    id: "progress-track-loader",
    name: "ProgressTrackLoader",
    category: "feedback",
    platform: "shared",
    styleTags: ["progress", "track", "green", "animated"],
    description: "Animated green progress track that fills and resets.",
    filePath: "components/evermade/feedback/ProgressTrackLoader.tsx",
    isMobileSafe: true,
    isDecorative: false,
  },
  {
    id: "emoji-reaction-menu",
    name: "EmojiReactionMenu",
    category: "feedback",
    platform: "shared",
    styleTags: ["emoji", "reaction", "dark", "tooltip"],
    description: "Emoji reaction bar with animated lift and tooltip labels.",
    filePath: "components/evermade/feedback/EmojiReactionMenu.tsx",
    isMobileSafe: true,
    isDecorative: false,
  },

  // ── Navigation ─────────────────────────────────────────────────────
  {
    id: "floating-icon-nav",
    name: "FloatingIconNav",
    category: "navigation",
    platform: "navigation",
    styleTags: ["dark", "icon", "floating", "bar"],
    description: "Dark floating icon navigation bar with hover lift.",
    filePath: "components/evermade/navigation/FloatingIconNav.tsx",
    isMobileSafe: true,
    isDecorative: false,
  },
  {
    id: "search-nav-input",
    name: "SearchNavInput",
    category: "navigation",
    platform: "navigation",
    styleTags: ["search", "nav", "rounded"],
    description: "Rounded nav search input with focus border transition.",
    filePath: "components/evermade/navigation/SearchNavInput.tsx",
    isMobileSafe: true,
    isDecorative: false,
  },
  {
    id: "frosted-bottom-nav",
    name: "FrostedBottomNav",
    category: "navigation",
    platform: "mobile",
    styleTags: ["frosted", "glass", "bottom-nav", "blur"],
    description: "Frosted glass bottom navigation bar with active states.",
    filePath: "components/evermade/navigation/FrostedBottomNav.tsx",
    isMobileSafe: true,
    isDecorative: false,
  },
  {
    id: "cyber-segment-nav",
    name: "CyberSegmentNav",
    category: "navigation",
    platform: "navigation",
    styleTags: ["cyber", "segment", "neon", "dark"],
    description: "Cyber-style segmented tab nav with neon sliding highlight.",
    filePath: "components/evermade/navigation/CyberSegmentNav.tsx",
    isMobileSafe: true,
    isDecorative: false,
  },

  // ── Data ──────────────────────────────────────────────────────────
  {
    id: "activity-list-item",
    name: "ActivityListItem",
    category: "data",
    platform: "shared",
    styleTags: ["list", "activity", "dark", "notification"],
    description: "Dark activity feed list item with gradient avatar.",
    filePath: "components/evermade/data/ActivityListItem.tsx",
    isMobileSafe: true,
    isDecorative: false,
  },
  {
    id: "stacked-notification-card",
    name: "StackedNotificationCard",
    category: "data",
    platform: "shared",
    styleTags: ["notification", "stacked", "glass", "dark"],
    description: "Three stacked glass notification cards with depth effect.",
    filePath: "components/evermade/data/StackedNotificationCard.tsx",
    isMobileSafe: false,
    isDecorative: false,
  },

  // ── Chat / AI ─────────────────────────────────────────────────────
  {
    id: "floating-chat-button",
    name: "FloatingChatButton",
    category: "chat",
    platform: "ai",
    styleTags: ["chat", "floating", "gradient", "tooltip"],
    description: "Gradient floating chat FAB with animated tooltip.",
    filePath: "components/evermade/chat/FloatingChatButton.tsx",
    isMobileSafe: true,
    isDecorative: false,
  },
  {
    id: "contact-ai-form",
    name: "ContactAiForm",
    category: "chat",
    platform: "ai",
    styleTags: ["contact", "form", "gradient", "dark"],
    description: "Dark contact form with gradient border and fire-orange accents.",
    filePath: "components/evermade/chat/ContactAiForm.tsx",
    isMobileSafe: false,
    isDecorative: false,
  },

  // ── Dashboard ─────────────────────────────────────────────────────
  {
    id: "crypto-dashboard-card",
    name: "CryptoDashboardCard",
    category: "dashboard",
    platform: "dashboard",
    styleTags: ["crypto", "chart", "dark", "animated"],
    description: "Crypto dashboard card with animated SVG chart and tab switching.",
    filePath: "components/evermade/dashboard/CryptoDashboardCard.tsx",
    isMobileSafe: false,
    isDecorative: false,
  },
  {
    id: "gradient-analytics-card",
    name: "GradientAnalyticsCard",
    category: "dashboard",
    platform: "dashboard",
    styleTags: ["analytics", "gradient", "bar-chart", "dark"],
    description: "Analytics card with gradient border, bar chart, and live badge.",
    filePath: "components/evermade/dashboard/GradientAnalyticsCard.tsx",
    isMobileSafe: false,
    isDecorative: false,
  },

  // ── Auth ──────────────────────────────────────────────────────────
  {
    id: "clean-auth-form",
    name: "CleanAuthForm",
    category: "mobile",
    platform: "auth",
    styleTags: ["auth", "clean", "white", "social"],
    description: "Clean white auth form with email/password and social buttons.",
    filePath: "components/evermade/mobile/CleanAuthForm.tsx",
    isMobileSafe: false,
    isDecorative: false,
  },
  {
    id: "soft-blue-auth-form",
    name: "SoftBlueAuthForm",
    category: "mobile",
    platform: "auth",
    styleTags: ["auth", "soft", "blue", "rounded"],
    description: "Soft blue rounded auth form with sky gradient sign-in button.",
    filePath: "components/evermade/mobile/SoftBlueAuthForm.tsx",
    isMobileSafe: true,
    isDecorative: false,
  },

  // ── Commerce ──────────────────────────────────────────────────────
  {
    id: "pro-pricing-card",
    name: "ProPricingCard",
    category: "commerce",
    platform: "commerce",
    styleTags: ["pricing", "pro", "gradient", "dark"],
    description: "Pro tier pricing card with gradient border and sparkle badge.",
    filePath: "components/evermade/commerce/ProPricingCard.tsx",
    isMobileSafe: true,
    isDecorative: false,
  },
  {
    id: "checkout-payment-form",
    name: "CheckoutPaymentForm",
    category: "commerce",
    platform: "commerce",
    styleTags: ["checkout", "payment", "dark", "card-form"],
    description: "Dark checkout payment form with animated focus labels.",
    filePath: "components/evermade/commerce/CheckoutPaymentForm.tsx",
    isMobileSafe: false,
    isDecorative: false,
  },
];

export default componentRegistry;
