import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/nextauth";

const MINIMAL_APP_JS = `import React from 'react';
import { View, Text, StyleSheet } from 'react-native';
export default function App() {
  return (
    <View style={styles.container}>
      <Text style={styles.text}>App Generated by Evermade</Text>
    </View>
  );
}
const styles = StyleSheet.create({
  container: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: '#000' },
  text: { color: '#fff', fontSize: 24 }
});`;

export async function POST(req: NextRequest) {
  const session = await getServerSession(authOptions);
  if (!session) return NextResponse.json({ error: "Authentication required" }, { status: 401 });

  const body = await req.json() as { appName?: string };
  const appName = body.appName ?? "My App";

  console.log("[Snack] creating snack for:", appName);

  const res = await fetch("https://snack.expo.dev/api/v2/snack", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      name: appName,
      description: "Generated by Evermade",
      sdkVersion: "52.0.0",
      files: {
        "App.js": { type: "CODE", contents: MINIMAL_APP_JS },
      },
    }),
  });

  const rawBody = await res.text();
  console.log("[Snack] response status:", res.status, "body:", rawBody.slice(0, 200));

  if (!res.ok) {
    return NextResponse.json({ error: `Snack API error ${res.status}: ${rawBody.slice(0, 100)}` }, { status: 502 });
  }

  let data: { hashId?: string };
  try {
    data = JSON.parse(rawBody) as { hashId?: string };
  } catch {
    return NextResponse.json({ error: "Snack API returned non-JSON" }, { status: 502 });
  }

  if (!data.hashId) {
    return NextResponse.json({ error: "Snack API did not return a hashId" }, { status: 502 });
  }

  console.log("[Snack] created:", data.hashId);
  return NextResponse.json({ hashId: data.hashId });
}
