import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/nextauth";

function buildSnackApp(appName: string, screenNames: string[]): string {
  const screens = JSON.stringify(screenNames);
  const safe = appName.replace(/'/g, "\\'");
  return `import React, { useState } from 'react';
import { View, Text, TouchableOpacity, StyleSheet, SafeAreaView, ScrollView } from 'react-native';

const SCREENS = ${screens};

function Screen({ name }) {
  return (
    <ScrollView contentContainerStyle={styles.screen}>
      <Text style={styles.screenTitle}>{name}</Text>
      <Text style={styles.screenSub}>Made with Evermade</Text>
    </ScrollView>
  );
}

export default function App() {
  const [active, setActive] = useState(0);
  return (
    <SafeAreaView style={styles.root}>
      <View style={styles.header}>
        <Text style={styles.appName}>${safe}</Text>
      </View>
      <View style={styles.content}>
        <Screen name={SCREENS[active]} />
      </View>
      <View style={styles.tabBar}>
        {SCREENS.map((name, i) => (
          <TouchableOpacity key={name} style={styles.tab} onPress={() => setActive(i)}>
            <View style={[styles.dot, active === i && styles.dotActive]} />
            <Text style={[styles.tabLabel, active === i && styles.tabLabelActive]} numberOfLines={1}>{name}</Text>
          </TouchableOpacity>
        ))}
      </View>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#09090b' },
  header: { paddingHorizontal: 20, paddingTop: 8, paddingBottom: 12, borderBottomWidth: 1, borderBottomColor: 'rgba(255,255,255,0.06)' },
  appName: { fontSize: 16, fontWeight: '700', color: 'rgba(255,255,255,0.85)', letterSpacing: -0.3 },
  content: { flex: 1 },
  screen: { flexGrow: 1, alignItems: 'center', justifyContent: 'center', padding: 24 },
  screenTitle: { fontSize: 28, fontWeight: '700', color: '#fff', marginBottom: 8, textAlign: 'center' },
  screenSub: { fontSize: 13, color: 'rgba(255,255,255,0.35)', textAlign: 'center' },
  tabBar: { flexDirection: 'row', borderTopWidth: 1, borderTopColor: 'rgba(255,255,255,0.08)', paddingBottom: 20, paddingTop: 10, backgroundColor: '#09090b' },
  tab: { flex: 1, alignItems: 'center', gap: 4, paddingHorizontal: 4 },
  dot: { width: 4, height: 4, borderRadius: 2, backgroundColor: 'rgba(255,255,255,0.15)' },
  dotActive: { backgroundColor: '#CCFF00' },
  tabLabel: { fontSize: 10, color: 'rgba(255,255,255,0.3)', textAlign: 'center' },
  tabLabelActive: { color: '#CCFF00', fontWeight: '600' },
});
`;
}

export async function POST(req: NextRequest) {
  const session = await getServerSession(authOptions);
  if (!session) return NextResponse.json({ error: "Authentication required" }, { status: 401 });

  const body = await req.json() as { appName?: string; screens?: Array<{ screenName: string }> };

  if (!body.appName || !Array.isArray(body.screens) || body.screens.length === 0) {
    return NextResponse.json({ error: "appName and screens required" }, { status: 400 });
  }

  const appJs = buildSnackApp(body.appName, body.screens.map((s) => s.screenName));

  const res = await fetch("https://exp.host/--/api/v2/snack", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      name: body.appName,
      description: "Generated by Evermade",
      sdkVersion: "52.0.0",
      files: {
        "App.js": { type: "CODE", contents: appJs },
      },
    }),
  });

  if (!res.ok) {
    const text = await res.text();
    console.error("[Snack] API error:", res.status, text.slice(0, 300));
    return NextResponse.json({ error: `Snack API error ${res.status}` }, { status: 502 });
  }

  const data = await res.json() as { hashId?: string };
  if (!data.hashId) {
    console.error("[Snack] No hashId in response:", JSON.stringify(data).slice(0, 200));
    return NextResponse.json({ error: "Snack API did not return a hashId" }, { status: 502 });
  }

  return NextResponse.json({ hashId: data.hashId });
}
